name: lsmash
channels:
  - conda-forge
dependencies:
  - python=3.12
  - boost
  - gsl
  - llvm-openmp
  - compilers
  - numpy
  - pandas
  - jupyterlab
  - pip
  - matplotlib
  - scipy
  - seaborn
  - yfinance
  - statsmodels
  - scikit-learn
  - pip:
    - pycwt
    - EMD-signal
    - pmdarima
  - pip:
    - pybind11>=2.11
    - setuptools>=69
    - wheel
